server:
  port: 8090

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

custom:
  # 替换成钉钉生成的机器人 token
  dingtalk-url: http://samin.dev/robot/send?access_token=xxx
  project-name: A市智慧园区项目