spring:
  application:
    name: samin-prometheus-test-app

# 启动后观测 http://localhost:8080/actuator/prometheus
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"