version: "3.8"

# dev/123456
# /install 界面配置的时候，不能修改内部监听端口 22 和 3000 ，否则重启失败（修改了内部端口，需要修改映射规则）

services:
  gogs:
    image: gogs/gogs:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8000:3000"
      - "1022:22"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: 2
    volumes:
      - /mnt/data/gogs:/data

  db:
    image: mysql:5.7
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: 2
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=gogs
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=gogs
    volumes:
      - /mnt/mysql/data:/var/lib/mysql