version: "3.8"

services:
  minio:
    container_name: minio
    restart: always
    image: minio/minio
    # 指定控制台地址
    command: server /data --console-address ":9001"
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: 2
    volumes:
      - /mnt/data/minio:/data
    ports:
      - 9000:9000
      - 9001:9001


# 最新版本 MinIO 把 WebUI 对于桶的配置移除，解耦操作，原操作由 mc 指令执行

# 配置实例
# mc alias list
# mc alias set local <URL> <APP_KEY> <APP_SECRET>

# 创建桶
# mc mb local/biz-bucket

# 配置桶策略
# mc anonymous set public local/biz-bucket