services:
  minio:
    container_name: minio
    restart: always
    image: minio/minio
    # 指定控制台地址
    command: server /data --console-address ":9001"
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: 2
    volumes:
      - /mnt/data/minio:/data
    ports:
      - 9000:9000
      - 9001:9001