version: "3.8"

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      # WebSocket
      - "9001:9001"
    volumes:
      - /mnt/data/mosquitto/config:/mosquitto/config
      - /mnt/data/mosquitto/data:/mosquitto/data
      - /mnt/data/mosquitto/log:/mosquitto/log
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: 2
    restart: always
    # 根据需要设置时区
    environment:
      - TZ=Asia/Shanghai

# 1. 编辑 config/mosquitto.conf

# allow_anonymous false
# listener 1883
# listener 9001
# protocol websockets
# persistence true
# password_file /mosquitto/config/pwfile
# persistence_file mosquitto.db
# persistence_location /mosquitto/data/

# 2. touch config/pwfile

# 3. docker exec -it mqtt_broker sh

# 4. mosquitto_passwd -c /mosquitto/config/pwfile user1

# 5. docker-compose restart

# 6. 连接 WS， 可以订阅查询服务器的实时状态
# $SYS/broker/clients/connected 当前连接的客户端数量
# $SYS/broker/subscriptions/count 服务器订阅主题总数