version: '3'

services:
  mysql5:
    container_name: mysql5.7
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: default
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: 2
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    # 指定卷的驱动类型
    driver: local
    driver_opts:
      # 使用本地文件系统
      type: none
      o: bind
      # 指定本地路径
      device: /mnt/data/mysql/data