version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    # 可以做一些定制化配置
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=1000
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: default
    ports:
      - '3306:3306'
    volumes:
      - '/mnt/data/mysql/data:/var/lib/mysql'
      - '/mnt/data/mysql/conf.d:/etc/mysql/conf.d'