version: '3'

services:
  mysql:
    container_name: mysql8
    restart: always
    image: mysql:8.0
    # 可以做一些定制化配置
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=1000
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: default
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'mysqladmin -uroot -prootpasswd -hlocalhost status || exit 1'"]
      interval: 10s
      timeout: 3s
      retries: 3
    # 也可以通过修改 daemon.json 来默认每个容器默认的配置
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: 2
    ports:
      - '3306:3306'
    volumes:
      - '/mnt/data/mysql/data:/var/lib/mysql'
      #- '/mnt/data/mysql/conf.d:/etc/mysql/conf.d'