version: "3.3"

services:
  nginx:
    container_name: nginx
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: 2
    restart: always
    image: nginx:1.19.4
    volumes:
      - /mnt/data/nginx/html:/usr/share/nginx/html
    ports:
      - 80:80