version: "3.3"

services:
  rabbitmq:
    container_name: rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: 2
    restart: always
    # 带控制台版本
    image: rabbitmq:3-management
    volumes:
      - /mnt/data/rabbitmq/data:/var/lib/rabbitmq
      - /mnt/data/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    ports:
      - "5672:5672"
      - "15672:15672"