version: "3.3"

services:
  minio:
    container_name: socks5
    restart: always
    image: xkuma/socks5
    environment:
      - PROXY_USER=samin
      - PROXY_PASSWORD=samin
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: 2
    ports:
      - 1080:1080