version: "3.3"

services:
  zlm:
    container_name: zlm
    restart: always
    image: zlmediakit/zlmediakit:master
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: 2
    ports:
      - 1935:1935
      - 8089:80
      - 8443:443
      - 8554:554
      - 10000:10000
      - 10000:10000/udp
      - 8000:8000/udp
      - 9000:9000/udp