server:
  port: 8081

nacos:
  config:
    server-addr: samin-use-case.local:8848

# 可以不写，默认为 true
custom:
  config:
    enabled: false
  pg_host: samin-use-case.local
  pg_port: 5432
  pg_database: samin-dev
  pg_username: auth
  pg_password: auth123456
  pg_schema: public
  redis_host: samin-use-case.local
  redis_port: 6379
  redis_password: dev_plat@123
  redis_database: 1

spring:
  datasource:
    url: jdbc:postgresql://${custom.pg_host}:${custom.pg_port}/${custom.pg_database}?currentSchema=${custom.pg_schema:public}&stringtype=unspecified
    username: ${custom.pg_username}
    password: ${custom.pg_password}
    driver-class-name: org.postgresql.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 50
    maxWait: 120000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  redis:
    host: ${custom.redis_host}
    port: ${custom.redis_port}
    password: ${custom.redis_password}
    database: ${custom.redis_database}
    lettuce:
      pool:
        min-idle: 5
        max-active: 10
        max-wait: 3000
  profiles:
    active: dev
  application:
    name: samin

use_case:
  values: value1,value2,value3