spring:
  application:
    name: samin-prometheus-test-app

# 启动后观测 http://localhost:8080/_mng/actuator/prometheus
management:
  server:
    port: 8081
    base-path: /_mng
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"