version: "3.3"

services:
    router-nginx:
        container_name: router-nginx
        restart: always
        image: nginx:1.19.4
        logging:
            driver: "json-file"
            options:
                max-size: "500m"
                max-file: 2
        volumes:
            - $PWD/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80