server:
  port: 8092

spring:
  application:
    name: job-worker-b
  rabbitmq:
    host: samin.local
    port: 5672
    username: job
    password: job
    virtual-host: job
    listener:
      simple:
        prefetch: 1
        default-requeue-rejected: false
        concurrency: 1
        max-concurrency: 10